
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Voter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Voter
 * 
 */
export type VoterModel = runtime.Types.Result.DefaultSelection<Prisma.$VoterPayload>

export type AggregateVoter = {
  _count: VoterCountAggregateOutputType | null
  _avg: VoterAvgAggregateOutputType | null
  _sum: VoterSumAggregateOutputType | null
  _min: VoterMinAggregateOutputType | null
  _max: VoterMaxAggregateOutputType | null
}

export type VoterAvgAggregateOutputType = {
  id: number | null
}

export type VoterSumAggregateOutputType = {
  id: number | null
}

export type VoterMinAggregateOutputType = {
  id: number | null
  phone: string | null
  name: string | null
  organization: string | null
  status: string | null
  created_at: Date | null
}

export type VoterMaxAggregateOutputType = {
  id: number | null
  phone: string | null
  name: string | null
  organization: string | null
  status: string | null
  created_at: Date | null
}

export type VoterCountAggregateOutputType = {
  id: number
  phone: number
  name: number
  organization: number
  status: number
  created_at: number
  _all: number
}


export type VoterAvgAggregateInputType = {
  id?: true
}

export type VoterSumAggregateInputType = {
  id?: true
}

export type VoterMinAggregateInputType = {
  id?: true
  phone?: true
  name?: true
  organization?: true
  status?: true
  created_at?: true
}

export type VoterMaxAggregateInputType = {
  id?: true
  phone?: true
  name?: true
  organization?: true
  status?: true
  created_at?: true
}

export type VoterCountAggregateInputType = {
  id?: true
  phone?: true
  name?: true
  organization?: true
  status?: true
  created_at?: true
  _all?: true
}

export type VoterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Voter to aggregate.
   */
  where?: Prisma.VoterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Voters to fetch.
   */
  orderBy?: Prisma.VoterOrderByWithRelationInput | Prisma.VoterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VoterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Voters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Voters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Voters
  **/
  _count?: true | VoterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VoterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VoterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VoterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VoterMaxAggregateInputType
}

export type GetVoterAggregateType<T extends VoterAggregateArgs> = {
      [P in keyof T & keyof AggregateVoter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVoter[P]>
    : Prisma.GetScalarType<T[P], AggregateVoter[P]>
}




export type VoterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VoterWhereInput
  orderBy?: Prisma.VoterOrderByWithAggregationInput | Prisma.VoterOrderByWithAggregationInput[]
  by: Prisma.VoterScalarFieldEnum[] | Prisma.VoterScalarFieldEnum
  having?: Prisma.VoterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VoterCountAggregateInputType | true
  _avg?: VoterAvgAggregateInputType
  _sum?: VoterSumAggregateInputType
  _min?: VoterMinAggregateInputType
  _max?: VoterMaxAggregateInputType
}

export type VoterGroupByOutputType = {
  id: number
  phone: string
  name: string
  organization: string
  status: string
  created_at: Date
  _count: VoterCountAggregateOutputType | null
  _avg: VoterAvgAggregateOutputType | null
  _sum: VoterSumAggregateOutputType | null
  _min: VoterMinAggregateOutputType | null
  _max: VoterMaxAggregateOutputType | null
}

type GetVoterGroupByPayload<T extends VoterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VoterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VoterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VoterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VoterGroupByOutputType[P]>
      }
    >
  >



export type VoterWhereInput = {
  AND?: Prisma.VoterWhereInput | Prisma.VoterWhereInput[]
  OR?: Prisma.VoterWhereInput[]
  NOT?: Prisma.VoterWhereInput | Prisma.VoterWhereInput[]
  id?: Prisma.IntFilter<"Voter"> | number
  phone?: Prisma.StringFilter<"Voter"> | string
  name?: Prisma.StringFilter<"Voter"> | string
  organization?: Prisma.StringFilter<"Voter"> | string
  status?: Prisma.StringFilter<"Voter"> | string
  created_at?: Prisma.DateTimeFilter<"Voter"> | Date | string
}

export type VoterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  name?: Prisma.SortOrder
  organization?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type VoterWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  phone?: string
  AND?: Prisma.VoterWhereInput | Prisma.VoterWhereInput[]
  OR?: Prisma.VoterWhereInput[]
  NOT?: Prisma.VoterWhereInput | Prisma.VoterWhereInput[]
  name?: Prisma.StringFilter<"Voter"> | string
  organization?: Prisma.StringFilter<"Voter"> | string
  status?: Prisma.StringFilter<"Voter"> | string
  created_at?: Prisma.DateTimeFilter<"Voter"> | Date | string
}, "id" | "phone">

export type VoterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  name?: Prisma.SortOrder
  organization?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.VoterCountOrderByAggregateInput
  _avg?: Prisma.VoterAvgOrderByAggregateInput
  _max?: Prisma.VoterMaxOrderByAggregateInput
  _min?: Prisma.VoterMinOrderByAggregateInput
  _sum?: Prisma.VoterSumOrderByAggregateInput
}

export type VoterScalarWhereWithAggregatesInput = {
  AND?: Prisma.VoterScalarWhereWithAggregatesInput | Prisma.VoterScalarWhereWithAggregatesInput[]
  OR?: Prisma.VoterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VoterScalarWhereWithAggregatesInput | Prisma.VoterScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Voter"> | number
  phone?: Prisma.StringWithAggregatesFilter<"Voter"> | string
  name?: Prisma.StringWithAggregatesFilter<"Voter"> | string
  organization?: Prisma.StringWithAggregatesFilter<"Voter"> | string
  status?: Prisma.StringWithAggregatesFilter<"Voter"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Voter"> | Date | string
}

export type VoterCreateInput = {
  phone: string
  name: string
  organization: string
  status?: string
  created_at?: Date | string
}

export type VoterUncheckedCreateInput = {
  id?: number
  phone: string
  name: string
  organization: string
  status?: string
  created_at?: Date | string
}

export type VoterUpdateInput = {
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  organization?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VoterUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  organization?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VoterCreateManyInput = {
  id?: number
  phone: string
  name: string
  organization: string
  status?: string
  created_at?: Date | string
}

export type VoterUpdateManyMutationInput = {
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  organization?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VoterUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  organization?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VoterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  name?: Prisma.SortOrder
  organization?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type VoterAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type VoterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  name?: Prisma.SortOrder
  organization?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type VoterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  name?: Prisma.SortOrder
  organization?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type VoterSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type VoterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  name?: boolean
  organization?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["voter"]>

export type VoterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  name?: boolean
  organization?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["voter"]>

export type VoterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  name?: boolean
  organization?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["voter"]>

export type VoterSelectScalar = {
  id?: boolean
  phone?: boolean
  name?: boolean
  organization?: boolean
  status?: boolean
  created_at?: boolean
}

export type VoterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "phone" | "name" | "organization" | "status" | "created_at", ExtArgs["result"]["voter"]>

export type $VoterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Voter"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    phone: string
    name: string
    organization: string
    status: string
    created_at: Date
  }, ExtArgs["result"]["voter"]>
  composites: {}
}

export type VoterGetPayload<S extends boolean | null | undefined | VoterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VoterPayload, S>

export type VoterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VoterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VoterCountAggregateInputType | true
  }

export interface VoterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Voter'], meta: { name: 'Voter' } }
  /**
   * Find zero or one Voter that matches the filter.
   * @param {VoterFindUniqueArgs} args - Arguments to find a Voter
   * @example
   * // Get one Voter
   * const voter = await prisma.voter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VoterFindUniqueArgs>(args: Prisma.SelectSubset<T, VoterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Voter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VoterFindUniqueOrThrowArgs} args - Arguments to find a Voter
   * @example
   * // Get one Voter
   * const voter = await prisma.voter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VoterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VoterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Voter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterFindFirstArgs} args - Arguments to find a Voter
   * @example
   * // Get one Voter
   * const voter = await prisma.voter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VoterFindFirstArgs>(args?: Prisma.SelectSubset<T, VoterFindFirstArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Voter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterFindFirstOrThrowArgs} args - Arguments to find a Voter
   * @example
   * // Get one Voter
   * const voter = await prisma.voter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VoterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VoterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Voters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Voters
   * const voters = await prisma.voter.findMany()
   * 
   * // Get first 10 Voters
   * const voters = await prisma.voter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const voterWithIdOnly = await prisma.voter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VoterFindManyArgs>(args?: Prisma.SelectSubset<T, VoterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Voter.
   * @param {VoterCreateArgs} args - Arguments to create a Voter.
   * @example
   * // Create one Voter
   * const Voter = await prisma.voter.create({
   *   data: {
   *     // ... data to create a Voter
   *   }
   * })
   * 
   */
  create<T extends VoterCreateArgs>(args: Prisma.SelectSubset<T, VoterCreateArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Voters.
   * @param {VoterCreateManyArgs} args - Arguments to create many Voters.
   * @example
   * // Create many Voters
   * const voter = await prisma.voter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VoterCreateManyArgs>(args?: Prisma.SelectSubset<T, VoterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Voters and returns the data saved in the database.
   * @param {VoterCreateManyAndReturnArgs} args - Arguments to create many Voters.
   * @example
   * // Create many Voters
   * const voter = await prisma.voter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Voters and only return the `id`
   * const voterWithIdOnly = await prisma.voter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VoterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VoterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Voter.
   * @param {VoterDeleteArgs} args - Arguments to delete one Voter.
   * @example
   * // Delete one Voter
   * const Voter = await prisma.voter.delete({
   *   where: {
   *     // ... filter to delete one Voter
   *   }
   * })
   * 
   */
  delete<T extends VoterDeleteArgs>(args: Prisma.SelectSubset<T, VoterDeleteArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Voter.
   * @param {VoterUpdateArgs} args - Arguments to update one Voter.
   * @example
   * // Update one Voter
   * const voter = await prisma.voter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VoterUpdateArgs>(args: Prisma.SelectSubset<T, VoterUpdateArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Voters.
   * @param {VoterDeleteManyArgs} args - Arguments to filter Voters to delete.
   * @example
   * // Delete a few Voters
   * const { count } = await prisma.voter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VoterDeleteManyArgs>(args?: Prisma.SelectSubset<T, VoterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Voters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Voters
   * const voter = await prisma.voter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VoterUpdateManyArgs>(args: Prisma.SelectSubset<T, VoterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Voters and returns the data updated in the database.
   * @param {VoterUpdateManyAndReturnArgs} args - Arguments to update many Voters.
   * @example
   * // Update many Voters
   * const voter = await prisma.voter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Voters and only return the `id`
   * const voterWithIdOnly = await prisma.voter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VoterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VoterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Voter.
   * @param {VoterUpsertArgs} args - Arguments to update or create a Voter.
   * @example
   * // Update or create a Voter
   * const voter = await prisma.voter.upsert({
   *   create: {
   *     // ... data to create a Voter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Voter we want to update
   *   }
   * })
   */
  upsert<T extends VoterUpsertArgs>(args: Prisma.SelectSubset<T, VoterUpsertArgs<ExtArgs>>): Prisma.Prisma__VoterClient<runtime.Types.Result.GetResult<Prisma.$VoterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Voters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterCountArgs} args - Arguments to filter Voters to count.
   * @example
   * // Count the number of Voters
   * const count = await prisma.voter.count({
   *   where: {
   *     // ... the filter for the Voters we want to count
   *   }
   * })
  **/
  count<T extends VoterCountArgs>(
    args?: Prisma.Subset<T, VoterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VoterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Voter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VoterAggregateArgs>(args: Prisma.Subset<T, VoterAggregateArgs>): Prisma.PrismaPromise<GetVoterAggregateType<T>>

  /**
   * Group by Voter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VoterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VoterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VoterGroupByArgs['orderBy'] }
      : { orderBy?: VoterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VoterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVoterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Voter model
 */
readonly fields: VoterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Voter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VoterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Voter model
 */
export interface VoterFieldRefs {
  readonly id: Prisma.FieldRef<"Voter", 'Int'>
  readonly phone: Prisma.FieldRef<"Voter", 'String'>
  readonly name: Prisma.FieldRef<"Voter", 'String'>
  readonly organization: Prisma.FieldRef<"Voter", 'String'>
  readonly status: Prisma.FieldRef<"Voter", 'String'>
  readonly created_at: Prisma.FieldRef<"Voter", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Voter findUnique
 */
export type VoterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter, which Voter to fetch.
   */
  where: Prisma.VoterWhereUniqueInput
}

/**
 * Voter findUniqueOrThrow
 */
export type VoterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter, which Voter to fetch.
   */
  where: Prisma.VoterWhereUniqueInput
}

/**
 * Voter findFirst
 */
export type VoterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter, which Voter to fetch.
   */
  where?: Prisma.VoterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Voters to fetch.
   */
  orderBy?: Prisma.VoterOrderByWithRelationInput | Prisma.VoterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Voters.
   */
  cursor?: Prisma.VoterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Voters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Voters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Voters.
   */
  distinct?: Prisma.VoterScalarFieldEnum | Prisma.VoterScalarFieldEnum[]
}

/**
 * Voter findFirstOrThrow
 */
export type VoterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter, which Voter to fetch.
   */
  where?: Prisma.VoterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Voters to fetch.
   */
  orderBy?: Prisma.VoterOrderByWithRelationInput | Prisma.VoterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Voters.
   */
  cursor?: Prisma.VoterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Voters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Voters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Voters.
   */
  distinct?: Prisma.VoterScalarFieldEnum | Prisma.VoterScalarFieldEnum[]
}

/**
 * Voter findMany
 */
export type VoterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter, which Voters to fetch.
   */
  where?: Prisma.VoterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Voters to fetch.
   */
  orderBy?: Prisma.VoterOrderByWithRelationInput | Prisma.VoterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Voters.
   */
  cursor?: Prisma.VoterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Voters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Voters.
   */
  skip?: number
  distinct?: Prisma.VoterScalarFieldEnum | Prisma.VoterScalarFieldEnum[]
}

/**
 * Voter create
 */
export type VoterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * The data needed to create a Voter.
   */
  data: Prisma.XOR<Prisma.VoterCreateInput, Prisma.VoterUncheckedCreateInput>
}

/**
 * Voter createMany
 */
export type VoterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Voters.
   */
  data: Prisma.VoterCreateManyInput | Prisma.VoterCreateManyInput[]
}

/**
 * Voter createManyAndReturn
 */
export type VoterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * The data used to create many Voters.
   */
  data: Prisma.VoterCreateManyInput | Prisma.VoterCreateManyInput[]
}

/**
 * Voter update
 */
export type VoterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * The data needed to update a Voter.
   */
  data: Prisma.XOR<Prisma.VoterUpdateInput, Prisma.VoterUncheckedUpdateInput>
  /**
   * Choose, which Voter to update.
   */
  where: Prisma.VoterWhereUniqueInput
}

/**
 * Voter updateMany
 */
export type VoterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Voters.
   */
  data: Prisma.XOR<Prisma.VoterUpdateManyMutationInput, Prisma.VoterUncheckedUpdateManyInput>
  /**
   * Filter which Voters to update
   */
  where?: Prisma.VoterWhereInput
  /**
   * Limit how many Voters to update.
   */
  limit?: number
}

/**
 * Voter updateManyAndReturn
 */
export type VoterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * The data used to update Voters.
   */
  data: Prisma.XOR<Prisma.VoterUpdateManyMutationInput, Prisma.VoterUncheckedUpdateManyInput>
  /**
   * Filter which Voters to update
   */
  where?: Prisma.VoterWhereInput
  /**
   * Limit how many Voters to update.
   */
  limit?: number
}

/**
 * Voter upsert
 */
export type VoterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * The filter to search for the Voter to update in case it exists.
   */
  where: Prisma.VoterWhereUniqueInput
  /**
   * In case the Voter found by the `where` argument doesn't exist, create a new Voter with this data.
   */
  create: Prisma.XOR<Prisma.VoterCreateInput, Prisma.VoterUncheckedCreateInput>
  /**
   * In case the Voter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VoterUpdateInput, Prisma.VoterUncheckedUpdateInput>
}

/**
 * Voter delete
 */
export type VoterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
  /**
   * Filter which Voter to delete.
   */
  where: Prisma.VoterWhereUniqueInput
}

/**
 * Voter deleteMany
 */
export type VoterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Voters to delete
   */
  where?: Prisma.VoterWhereInput
  /**
   * Limit how many Voters to delete.
   */
  limit?: number
}

/**
 * Voter without action
 */
export type VoterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Voter
   */
  select?: Prisma.VoterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Voter
   */
  omit?: Prisma.VoterOmit<ExtArgs> | null
}
