
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MessageQueue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MessageQueue
 * 
 */
export type MessageQueueModel = runtime.Types.Result.DefaultSelection<Prisma.$MessageQueuePayload>

export type AggregateMessageQueue = {
  _count: MessageQueueCountAggregateOutputType | null
  _avg: MessageQueueAvgAggregateOutputType | null
  _sum: MessageQueueSumAggregateOutputType | null
  _min: MessageQueueMinAggregateOutputType | null
  _max: MessageQueueMaxAggregateOutputType | null
}

export type MessageQueueAvgAggregateOutputType = {
  id: number | null
  attempts: number | null
}

export type MessageQueueSumAggregateOutputType = {
  id: number | null
  attempts: number | null
}

export type MessageQueueMinAggregateOutputType = {
  id: number | null
  phone: string | null
  message: string | null
  status: string | null
  attempts: number | null
  error: string | null
  created_at: Date | null
  sent_at: Date | null
}

export type MessageQueueMaxAggregateOutputType = {
  id: number | null
  phone: string | null
  message: string | null
  status: string | null
  attempts: number | null
  error: string | null
  created_at: Date | null
  sent_at: Date | null
}

export type MessageQueueCountAggregateOutputType = {
  id: number
  phone: number
  message: number
  status: number
  attempts: number
  error: number
  created_at: number
  sent_at: number
  _all: number
}


export type MessageQueueAvgAggregateInputType = {
  id?: true
  attempts?: true
}

export type MessageQueueSumAggregateInputType = {
  id?: true
  attempts?: true
}

export type MessageQueueMinAggregateInputType = {
  id?: true
  phone?: true
  message?: true
  status?: true
  attempts?: true
  error?: true
  created_at?: true
  sent_at?: true
}

export type MessageQueueMaxAggregateInputType = {
  id?: true
  phone?: true
  message?: true
  status?: true
  attempts?: true
  error?: true
  created_at?: true
  sent_at?: true
}

export type MessageQueueCountAggregateInputType = {
  id?: true
  phone?: true
  message?: true
  status?: true
  attempts?: true
  error?: true
  created_at?: true
  sent_at?: true
  _all?: true
}

export type MessageQueueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageQueue to aggregate.
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageQueues to fetch.
   */
  orderBy?: Prisma.MessageQueueOrderByWithRelationInput | Prisma.MessageQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessageQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MessageQueues
  **/
  _count?: true | MessageQueueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MessageQueueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MessageQueueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessageQueueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessageQueueMaxAggregateInputType
}

export type GetMessageQueueAggregateType<T extends MessageQueueAggregateArgs> = {
      [P in keyof T & keyof AggregateMessageQueue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessageQueue[P]>
    : Prisma.GetScalarType<T[P], AggregateMessageQueue[P]>
}




export type MessageQueueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageQueueWhereInput
  orderBy?: Prisma.MessageQueueOrderByWithAggregationInput | Prisma.MessageQueueOrderByWithAggregationInput[]
  by: Prisma.MessageQueueScalarFieldEnum[] | Prisma.MessageQueueScalarFieldEnum
  having?: Prisma.MessageQueueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessageQueueCountAggregateInputType | true
  _avg?: MessageQueueAvgAggregateInputType
  _sum?: MessageQueueSumAggregateInputType
  _min?: MessageQueueMinAggregateInputType
  _max?: MessageQueueMaxAggregateInputType
}

export type MessageQueueGroupByOutputType = {
  id: number
  phone: string
  message: string
  status: string
  attempts: number
  error: string | null
  created_at: Date
  sent_at: Date | null
  _count: MessageQueueCountAggregateOutputType | null
  _avg: MessageQueueAvgAggregateOutputType | null
  _sum: MessageQueueSumAggregateOutputType | null
  _min: MessageQueueMinAggregateOutputType | null
  _max: MessageQueueMaxAggregateOutputType | null
}

type GetMessageQueueGroupByPayload<T extends MessageQueueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessageQueueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessageQueueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessageQueueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessageQueueGroupByOutputType[P]>
      }
    >
  >



export type MessageQueueWhereInput = {
  AND?: Prisma.MessageQueueWhereInput | Prisma.MessageQueueWhereInput[]
  OR?: Prisma.MessageQueueWhereInput[]
  NOT?: Prisma.MessageQueueWhereInput | Prisma.MessageQueueWhereInput[]
  id?: Prisma.IntFilter<"MessageQueue"> | number
  phone?: Prisma.StringFilter<"MessageQueue"> | string
  message?: Prisma.StringFilter<"MessageQueue"> | string
  status?: Prisma.StringFilter<"MessageQueue"> | string
  attempts?: Prisma.IntFilter<"MessageQueue"> | number
  error?: Prisma.StringNullableFilter<"MessageQueue"> | string | null
  created_at?: Prisma.DateTimeFilter<"MessageQueue"> | Date | string
  sent_at?: Prisma.DateTimeNullableFilter<"MessageQueue"> | Date | string | null
}

export type MessageQueueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type MessageQueueWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MessageQueueWhereInput | Prisma.MessageQueueWhereInput[]
  OR?: Prisma.MessageQueueWhereInput[]
  NOT?: Prisma.MessageQueueWhereInput | Prisma.MessageQueueWhereInput[]
  phone?: Prisma.StringFilter<"MessageQueue"> | string
  message?: Prisma.StringFilter<"MessageQueue"> | string
  status?: Prisma.StringFilter<"MessageQueue"> | string
  attempts?: Prisma.IntFilter<"MessageQueue"> | number
  error?: Prisma.StringNullableFilter<"MessageQueue"> | string | null
  created_at?: Prisma.DateTimeFilter<"MessageQueue"> | Date | string
  sent_at?: Prisma.DateTimeNullableFilter<"MessageQueue"> | Date | string | null
}, "id">

export type MessageQueueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MessageQueueCountOrderByAggregateInput
  _avg?: Prisma.MessageQueueAvgOrderByAggregateInput
  _max?: Prisma.MessageQueueMaxOrderByAggregateInput
  _min?: Prisma.MessageQueueMinOrderByAggregateInput
  _sum?: Prisma.MessageQueueSumOrderByAggregateInput
}

export type MessageQueueScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessageQueueScalarWhereWithAggregatesInput | Prisma.MessageQueueScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessageQueueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessageQueueScalarWhereWithAggregatesInput | Prisma.MessageQueueScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MessageQueue"> | number
  phone?: Prisma.StringWithAggregatesFilter<"MessageQueue"> | string
  message?: Prisma.StringWithAggregatesFilter<"MessageQueue"> | string
  status?: Prisma.StringWithAggregatesFilter<"MessageQueue"> | string
  attempts?: Prisma.IntWithAggregatesFilter<"MessageQueue"> | number
  error?: Prisma.StringNullableWithAggregatesFilter<"MessageQueue"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"MessageQueue"> | Date | string
  sent_at?: Prisma.DateTimeNullableWithAggregatesFilter<"MessageQueue"> | Date | string | null
}

export type MessageQueueCreateInput = {
  phone: string
  message: string
  status?: string
  attempts?: number
  error?: string | null
  created_at?: Date | string
  sent_at?: Date | string | null
}

export type MessageQueueUncheckedCreateInput = {
  id?: number
  phone: string
  message: string
  status?: string
  attempts?: number
  error?: string | null
  created_at?: Date | string
  sent_at?: Date | string | null
}

export type MessageQueueUpdateInput = {
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MessageQueueUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MessageQueueCreateManyInput = {
  id?: number
  phone: string
  message: string
  status?: string
  attempts?: number
  error?: string | null
  created_at?: Date | string
  sent_at?: Date | string | null
}

export type MessageQueueUpdateManyMutationInput = {
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MessageQueueUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MessageQueueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  error?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type MessageQueueAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type MessageQueueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  error?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type MessageQueueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  error?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type MessageQueueSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type MessageQueueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attempts?: boolean
  error?: boolean
  created_at?: boolean
  sent_at?: boolean
}, ExtArgs["result"]["messageQueue"]>

export type MessageQueueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attempts?: boolean
  error?: boolean
  created_at?: boolean
  sent_at?: boolean
}, ExtArgs["result"]["messageQueue"]>

export type MessageQueueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attempts?: boolean
  error?: boolean
  created_at?: boolean
  sent_at?: boolean
}, ExtArgs["result"]["messageQueue"]>

export type MessageQueueSelectScalar = {
  id?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attempts?: boolean
  error?: boolean
  created_at?: boolean
  sent_at?: boolean
}

export type MessageQueueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "phone" | "message" | "status" | "attempts" | "error" | "created_at" | "sent_at", ExtArgs["result"]["messageQueue"]>

export type $MessageQueuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MessageQueue"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    phone: string
    message: string
    status: string
    attempts: number
    error: string | null
    created_at: Date
    sent_at: Date | null
  }, ExtArgs["result"]["messageQueue"]>
  composites: {}
}

export type MessageQueueGetPayload<S extends boolean | null | undefined | MessageQueueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload, S>

export type MessageQueueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessageQueueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessageQueueCountAggregateInputType | true
  }

export interface MessageQueueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MessageQueue'], meta: { name: 'MessageQueue' } }
  /**
   * Find zero or one MessageQueue that matches the filter.
   * @param {MessageQueueFindUniqueArgs} args - Arguments to find a MessageQueue
   * @example
   * // Get one MessageQueue
   * const messageQueue = await prisma.messageQueue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessageQueueFindUniqueArgs>(args: Prisma.SelectSubset<T, MessageQueueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MessageQueue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessageQueueFindUniqueOrThrowArgs} args - Arguments to find a MessageQueue
   * @example
   * // Get one MessageQueue
   * const messageQueue = await prisma.messageQueue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessageQueueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessageQueueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageQueue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueFindFirstArgs} args - Arguments to find a MessageQueue
   * @example
   * // Get one MessageQueue
   * const messageQueue = await prisma.messageQueue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessageQueueFindFirstArgs>(args?: Prisma.SelectSubset<T, MessageQueueFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageQueue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueFindFirstOrThrowArgs} args - Arguments to find a MessageQueue
   * @example
   * // Get one MessageQueue
   * const messageQueue = await prisma.messageQueue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessageQueueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessageQueueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MessageQueues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MessageQueues
   * const messageQueues = await prisma.messageQueue.findMany()
   * 
   * // Get first 10 MessageQueues
   * const messageQueues = await prisma.messageQueue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messageQueueWithIdOnly = await prisma.messageQueue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MessageQueueFindManyArgs>(args?: Prisma.SelectSubset<T, MessageQueueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MessageQueue.
   * @param {MessageQueueCreateArgs} args - Arguments to create a MessageQueue.
   * @example
   * // Create one MessageQueue
   * const MessageQueue = await prisma.messageQueue.create({
   *   data: {
   *     // ... data to create a MessageQueue
   *   }
   * })
   * 
   */
  create<T extends MessageQueueCreateArgs>(args: Prisma.SelectSubset<T, MessageQueueCreateArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MessageQueues.
   * @param {MessageQueueCreateManyArgs} args - Arguments to create many MessageQueues.
   * @example
   * // Create many MessageQueues
   * const messageQueue = await prisma.messageQueue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessageQueueCreateManyArgs>(args?: Prisma.SelectSubset<T, MessageQueueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MessageQueues and returns the data saved in the database.
   * @param {MessageQueueCreateManyAndReturnArgs} args - Arguments to create many MessageQueues.
   * @example
   * // Create many MessageQueues
   * const messageQueue = await prisma.messageQueue.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MessageQueues and only return the `id`
   * const messageQueueWithIdOnly = await prisma.messageQueue.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MessageQueueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MessageQueueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MessageQueue.
   * @param {MessageQueueDeleteArgs} args - Arguments to delete one MessageQueue.
   * @example
   * // Delete one MessageQueue
   * const MessageQueue = await prisma.messageQueue.delete({
   *   where: {
   *     // ... filter to delete one MessageQueue
   *   }
   * })
   * 
   */
  delete<T extends MessageQueueDeleteArgs>(args: Prisma.SelectSubset<T, MessageQueueDeleteArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MessageQueue.
   * @param {MessageQueueUpdateArgs} args - Arguments to update one MessageQueue.
   * @example
   * // Update one MessageQueue
   * const messageQueue = await prisma.messageQueue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessageQueueUpdateArgs>(args: Prisma.SelectSubset<T, MessageQueueUpdateArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MessageQueues.
   * @param {MessageQueueDeleteManyArgs} args - Arguments to filter MessageQueues to delete.
   * @example
   * // Delete a few MessageQueues
   * const { count } = await prisma.messageQueue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessageQueueDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessageQueueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MessageQueues
   * const messageQueue = await prisma.messageQueue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessageQueueUpdateManyArgs>(args: Prisma.SelectSubset<T, MessageQueueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageQueues and returns the data updated in the database.
   * @param {MessageQueueUpdateManyAndReturnArgs} args - Arguments to update many MessageQueues.
   * @example
   * // Update many MessageQueues
   * const messageQueue = await prisma.messageQueue.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MessageQueues and only return the `id`
   * const messageQueueWithIdOnly = await prisma.messageQueue.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MessageQueueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MessageQueueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MessageQueue.
   * @param {MessageQueueUpsertArgs} args - Arguments to update or create a MessageQueue.
   * @example
   * // Update or create a MessageQueue
   * const messageQueue = await prisma.messageQueue.upsert({
   *   create: {
   *     // ... data to create a MessageQueue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MessageQueue we want to update
   *   }
   * })
   */
  upsert<T extends MessageQueueUpsertArgs>(args: Prisma.SelectSubset<T, MessageQueueUpsertArgs<ExtArgs>>): Prisma.Prisma__MessageQueueClient<runtime.Types.Result.GetResult<Prisma.$MessageQueuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MessageQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueCountArgs} args - Arguments to filter MessageQueues to count.
   * @example
   * // Count the number of MessageQueues
   * const count = await prisma.messageQueue.count({
   *   where: {
   *     // ... the filter for the MessageQueues we want to count
   *   }
   * })
  **/
  count<T extends MessageQueueCountArgs>(
    args?: Prisma.Subset<T, MessageQueueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessageQueueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MessageQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessageQueueAggregateArgs>(args: Prisma.Subset<T, MessageQueueAggregateArgs>): Prisma.PrismaPromise<GetMessageQueueAggregateType<T>>

  /**
   * Group by MessageQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageQueueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessageQueueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessageQueueGroupByArgs['orderBy'] }
      : { orderBy?: MessageQueueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessageQueueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessageQueueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MessageQueue model
 */
readonly fields: MessageQueueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MessageQueue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessageQueueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MessageQueue model
 */
export interface MessageQueueFieldRefs {
  readonly id: Prisma.FieldRef<"MessageQueue", 'Int'>
  readonly phone: Prisma.FieldRef<"MessageQueue", 'String'>
  readonly message: Prisma.FieldRef<"MessageQueue", 'String'>
  readonly status: Prisma.FieldRef<"MessageQueue", 'String'>
  readonly attempts: Prisma.FieldRef<"MessageQueue", 'Int'>
  readonly error: Prisma.FieldRef<"MessageQueue", 'String'>
  readonly created_at: Prisma.FieldRef<"MessageQueue", 'DateTime'>
  readonly sent_at: Prisma.FieldRef<"MessageQueue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MessageQueue findUnique
 */
export type MessageQueueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter, which MessageQueue to fetch.
   */
  where: Prisma.MessageQueueWhereUniqueInput
}

/**
 * MessageQueue findUniqueOrThrow
 */
export type MessageQueueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter, which MessageQueue to fetch.
   */
  where: Prisma.MessageQueueWhereUniqueInput
}

/**
 * MessageQueue findFirst
 */
export type MessageQueueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter, which MessageQueue to fetch.
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageQueues to fetch.
   */
  orderBy?: Prisma.MessageQueueOrderByWithRelationInput | Prisma.MessageQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageQueues.
   */
  cursor?: Prisma.MessageQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageQueues.
   */
  distinct?: Prisma.MessageQueueScalarFieldEnum | Prisma.MessageQueueScalarFieldEnum[]
}

/**
 * MessageQueue findFirstOrThrow
 */
export type MessageQueueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter, which MessageQueue to fetch.
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageQueues to fetch.
   */
  orderBy?: Prisma.MessageQueueOrderByWithRelationInput | Prisma.MessageQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageQueues.
   */
  cursor?: Prisma.MessageQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageQueues.
   */
  distinct?: Prisma.MessageQueueScalarFieldEnum | Prisma.MessageQueueScalarFieldEnum[]
}

/**
 * MessageQueue findMany
 */
export type MessageQueueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter, which MessageQueues to fetch.
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageQueues to fetch.
   */
  orderBy?: Prisma.MessageQueueOrderByWithRelationInput | Prisma.MessageQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MessageQueues.
   */
  cursor?: Prisma.MessageQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageQueues.
   */
  skip?: number
  distinct?: Prisma.MessageQueueScalarFieldEnum | Prisma.MessageQueueScalarFieldEnum[]
}

/**
 * MessageQueue create
 */
export type MessageQueueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * The data needed to create a MessageQueue.
   */
  data: Prisma.XOR<Prisma.MessageQueueCreateInput, Prisma.MessageQueueUncheckedCreateInput>
}

/**
 * MessageQueue createMany
 */
export type MessageQueueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MessageQueues.
   */
  data: Prisma.MessageQueueCreateManyInput | Prisma.MessageQueueCreateManyInput[]
}

/**
 * MessageQueue createManyAndReturn
 */
export type MessageQueueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * The data used to create many MessageQueues.
   */
  data: Prisma.MessageQueueCreateManyInput | Prisma.MessageQueueCreateManyInput[]
}

/**
 * MessageQueue update
 */
export type MessageQueueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * The data needed to update a MessageQueue.
   */
  data: Prisma.XOR<Prisma.MessageQueueUpdateInput, Prisma.MessageQueueUncheckedUpdateInput>
  /**
   * Choose, which MessageQueue to update.
   */
  where: Prisma.MessageQueueWhereUniqueInput
}

/**
 * MessageQueue updateMany
 */
export type MessageQueueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MessageQueues.
   */
  data: Prisma.XOR<Prisma.MessageQueueUpdateManyMutationInput, Prisma.MessageQueueUncheckedUpdateManyInput>
  /**
   * Filter which MessageQueues to update
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * Limit how many MessageQueues to update.
   */
  limit?: number
}

/**
 * MessageQueue updateManyAndReturn
 */
export type MessageQueueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * The data used to update MessageQueues.
   */
  data: Prisma.XOR<Prisma.MessageQueueUpdateManyMutationInput, Prisma.MessageQueueUncheckedUpdateManyInput>
  /**
   * Filter which MessageQueues to update
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * Limit how many MessageQueues to update.
   */
  limit?: number
}

/**
 * MessageQueue upsert
 */
export type MessageQueueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * The filter to search for the MessageQueue to update in case it exists.
   */
  where: Prisma.MessageQueueWhereUniqueInput
  /**
   * In case the MessageQueue found by the `where` argument doesn't exist, create a new MessageQueue with this data.
   */
  create: Prisma.XOR<Prisma.MessageQueueCreateInput, Prisma.MessageQueueUncheckedCreateInput>
  /**
   * In case the MessageQueue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessageQueueUpdateInput, Prisma.MessageQueueUncheckedUpdateInput>
}

/**
 * MessageQueue delete
 */
export type MessageQueueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
  /**
   * Filter which MessageQueue to delete.
   */
  where: Prisma.MessageQueueWhereUniqueInput
}

/**
 * MessageQueue deleteMany
 */
export type MessageQueueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageQueues to delete
   */
  where?: Prisma.MessageQueueWhereInput
  /**
   * Limit how many MessageQueues to delete.
   */
  limit?: number
}

/**
 * MessageQueue without action
 */
export type MessageQueueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageQueue
   */
  select?: Prisma.MessageQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageQueue
   */
  omit?: Prisma.MessageQueueOmit<ExtArgs> | null
}
