
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApiUrl` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApiUrl
 * 
 */
export type ApiUrlModel = runtime.Types.Result.DefaultSelection<Prisma.$ApiUrlPayload>

export type AggregateApiUrl = {
  _count: ApiUrlCountAggregateOutputType | null
  _min: ApiUrlMinAggregateOutputType | null
  _max: ApiUrlMaxAggregateOutputType | null
}

export type ApiUrlMinAggregateOutputType = {
  id: string | null
  url: string | null
}

export type ApiUrlMaxAggregateOutputType = {
  id: string | null
  url: string | null
}

export type ApiUrlCountAggregateOutputType = {
  id: number
  url: number
  _all: number
}


export type ApiUrlMinAggregateInputType = {
  id?: true
  url?: true
}

export type ApiUrlMaxAggregateInputType = {
  id?: true
  url?: true
}

export type ApiUrlCountAggregateInputType = {
  id?: true
  url?: true
  _all?: true
}

export type ApiUrlAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApiUrl to aggregate.
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiUrls to fetch.
   */
  orderBy?: Prisma.ApiUrlOrderByWithRelationInput | Prisma.ApiUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApiUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApiUrls
  **/
  _count?: true | ApiUrlCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApiUrlMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApiUrlMaxAggregateInputType
}

export type GetApiUrlAggregateType<T extends ApiUrlAggregateArgs> = {
      [P in keyof T & keyof AggregateApiUrl]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApiUrl[P]>
    : Prisma.GetScalarType<T[P], AggregateApiUrl[P]>
}




export type ApiUrlGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApiUrlWhereInput
  orderBy?: Prisma.ApiUrlOrderByWithAggregationInput | Prisma.ApiUrlOrderByWithAggregationInput[]
  by: Prisma.ApiUrlScalarFieldEnum[] | Prisma.ApiUrlScalarFieldEnum
  having?: Prisma.ApiUrlScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApiUrlCountAggregateInputType | true
  _min?: ApiUrlMinAggregateInputType
  _max?: ApiUrlMaxAggregateInputType
}

export type ApiUrlGroupByOutputType = {
  id: string
  url: string
  _count: ApiUrlCountAggregateOutputType | null
  _min: ApiUrlMinAggregateOutputType | null
  _max: ApiUrlMaxAggregateOutputType | null
}

type GetApiUrlGroupByPayload<T extends ApiUrlGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApiUrlGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApiUrlGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApiUrlGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApiUrlGroupByOutputType[P]>
      }
    >
  >



export type ApiUrlWhereInput = {
  AND?: Prisma.ApiUrlWhereInput | Prisma.ApiUrlWhereInput[]
  OR?: Prisma.ApiUrlWhereInput[]
  NOT?: Prisma.ApiUrlWhereInput | Prisma.ApiUrlWhereInput[]
  id?: Prisma.StringFilter<"ApiUrl"> | string
  url?: Prisma.StringFilter<"ApiUrl"> | string
}

export type ApiUrlOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type ApiUrlWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApiUrlWhereInput | Prisma.ApiUrlWhereInput[]
  OR?: Prisma.ApiUrlWhereInput[]
  NOT?: Prisma.ApiUrlWhereInput | Prisma.ApiUrlWhereInput[]
  url?: Prisma.StringFilter<"ApiUrl"> | string
}, "id">

export type ApiUrlOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  _count?: Prisma.ApiUrlCountOrderByAggregateInput
  _max?: Prisma.ApiUrlMaxOrderByAggregateInput
  _min?: Prisma.ApiUrlMinOrderByAggregateInput
}

export type ApiUrlScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApiUrlScalarWhereWithAggregatesInput | Prisma.ApiUrlScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApiUrlScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApiUrlScalarWhereWithAggregatesInput | Prisma.ApiUrlScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApiUrl"> | string
  url?: Prisma.StringWithAggregatesFilter<"ApiUrl"> | string
}

export type ApiUrlCreateInput = {
  id: string
  url: string
}

export type ApiUrlUncheckedCreateInput = {
  id: string
  url: string
}

export type ApiUrlUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ApiUrlUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ApiUrlCreateManyInput = {
  id: string
  url: string
}

export type ApiUrlUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ApiUrlUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ApiUrlCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type ApiUrlMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type ApiUrlMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
}



export type ApiUrlSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
}, ExtArgs["result"]["apiUrl"]>

export type ApiUrlSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
}, ExtArgs["result"]["apiUrl"]>

export type ApiUrlSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
}, ExtArgs["result"]["apiUrl"]>

export type ApiUrlSelectScalar = {
  id?: boolean
  url?: boolean
}

export type ApiUrlOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url", ExtArgs["result"]["apiUrl"]>

export type $ApiUrlPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApiUrl"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
  }, ExtArgs["result"]["apiUrl"]>
  composites: {}
}

export type ApiUrlGetPayload<S extends boolean | null | undefined | ApiUrlDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload, S>

export type ApiUrlCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApiUrlFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApiUrlCountAggregateInputType | true
  }

export interface ApiUrlDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApiUrl'], meta: { name: 'ApiUrl' } }
  /**
   * Find zero or one ApiUrl that matches the filter.
   * @param {ApiUrlFindUniqueArgs} args - Arguments to find a ApiUrl
   * @example
   * // Get one ApiUrl
   * const apiUrl = await prisma.apiUrl.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApiUrlFindUniqueArgs>(args: Prisma.SelectSubset<T, ApiUrlFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApiUrl that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApiUrlFindUniqueOrThrowArgs} args - Arguments to find a ApiUrl
   * @example
   * // Get one ApiUrl
   * const apiUrl = await prisma.apiUrl.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApiUrlFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApiUrlFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApiUrl that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlFindFirstArgs} args - Arguments to find a ApiUrl
   * @example
   * // Get one ApiUrl
   * const apiUrl = await prisma.apiUrl.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApiUrlFindFirstArgs>(args?: Prisma.SelectSubset<T, ApiUrlFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApiUrl that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlFindFirstOrThrowArgs} args - Arguments to find a ApiUrl
   * @example
   * // Get one ApiUrl
   * const apiUrl = await prisma.apiUrl.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApiUrlFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApiUrlFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApiUrls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApiUrls
   * const apiUrls = await prisma.apiUrl.findMany()
   * 
   * // Get first 10 ApiUrls
   * const apiUrls = await prisma.apiUrl.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const apiUrlWithIdOnly = await prisma.apiUrl.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApiUrlFindManyArgs>(args?: Prisma.SelectSubset<T, ApiUrlFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApiUrl.
   * @param {ApiUrlCreateArgs} args - Arguments to create a ApiUrl.
   * @example
   * // Create one ApiUrl
   * const ApiUrl = await prisma.apiUrl.create({
   *   data: {
   *     // ... data to create a ApiUrl
   *   }
   * })
   * 
   */
  create<T extends ApiUrlCreateArgs>(args: Prisma.SelectSubset<T, ApiUrlCreateArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApiUrls.
   * @param {ApiUrlCreateManyArgs} args - Arguments to create many ApiUrls.
   * @example
   * // Create many ApiUrls
   * const apiUrl = await prisma.apiUrl.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApiUrlCreateManyArgs>(args?: Prisma.SelectSubset<T, ApiUrlCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApiUrls and returns the data saved in the database.
   * @param {ApiUrlCreateManyAndReturnArgs} args - Arguments to create many ApiUrls.
   * @example
   * // Create many ApiUrls
   * const apiUrl = await prisma.apiUrl.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApiUrls and only return the `id`
   * const apiUrlWithIdOnly = await prisma.apiUrl.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApiUrlCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApiUrlCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApiUrl.
   * @param {ApiUrlDeleteArgs} args - Arguments to delete one ApiUrl.
   * @example
   * // Delete one ApiUrl
   * const ApiUrl = await prisma.apiUrl.delete({
   *   where: {
   *     // ... filter to delete one ApiUrl
   *   }
   * })
   * 
   */
  delete<T extends ApiUrlDeleteArgs>(args: Prisma.SelectSubset<T, ApiUrlDeleteArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApiUrl.
   * @param {ApiUrlUpdateArgs} args - Arguments to update one ApiUrl.
   * @example
   * // Update one ApiUrl
   * const apiUrl = await prisma.apiUrl.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApiUrlUpdateArgs>(args: Prisma.SelectSubset<T, ApiUrlUpdateArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApiUrls.
   * @param {ApiUrlDeleteManyArgs} args - Arguments to filter ApiUrls to delete.
   * @example
   * // Delete a few ApiUrls
   * const { count } = await prisma.apiUrl.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApiUrlDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApiUrlDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApiUrls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApiUrls
   * const apiUrl = await prisma.apiUrl.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApiUrlUpdateManyArgs>(args: Prisma.SelectSubset<T, ApiUrlUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApiUrls and returns the data updated in the database.
   * @param {ApiUrlUpdateManyAndReturnArgs} args - Arguments to update many ApiUrls.
   * @example
   * // Update many ApiUrls
   * const apiUrl = await prisma.apiUrl.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApiUrls and only return the `id`
   * const apiUrlWithIdOnly = await prisma.apiUrl.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApiUrlUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApiUrlUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApiUrl.
   * @param {ApiUrlUpsertArgs} args - Arguments to update or create a ApiUrl.
   * @example
   * // Update or create a ApiUrl
   * const apiUrl = await prisma.apiUrl.upsert({
   *   create: {
   *     // ... data to create a ApiUrl
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApiUrl we want to update
   *   }
   * })
   */
  upsert<T extends ApiUrlUpsertArgs>(args: Prisma.SelectSubset<T, ApiUrlUpsertArgs<ExtArgs>>): Prisma.Prisma__ApiUrlClient<runtime.Types.Result.GetResult<Prisma.$ApiUrlPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApiUrls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlCountArgs} args - Arguments to filter ApiUrls to count.
   * @example
   * // Count the number of ApiUrls
   * const count = await prisma.apiUrl.count({
   *   where: {
   *     // ... the filter for the ApiUrls we want to count
   *   }
   * })
  **/
  count<T extends ApiUrlCountArgs>(
    args?: Prisma.Subset<T, ApiUrlCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApiUrlCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApiUrl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApiUrlAggregateArgs>(args: Prisma.Subset<T, ApiUrlAggregateArgs>): Prisma.PrismaPromise<GetApiUrlAggregateType<T>>

  /**
   * Group by ApiUrl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiUrlGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApiUrlGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApiUrlGroupByArgs['orderBy'] }
      : { orderBy?: ApiUrlGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApiUrlGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApiUrlGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApiUrl model
 */
readonly fields: ApiUrlFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApiUrl.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApiUrlClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApiUrl model
 */
export interface ApiUrlFieldRefs {
  readonly id: Prisma.FieldRef<"ApiUrl", 'String'>
  readonly url: Prisma.FieldRef<"ApiUrl", 'String'>
}
    

// Custom InputTypes
/**
 * ApiUrl findUnique
 */
export type ApiUrlFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter, which ApiUrl to fetch.
   */
  where: Prisma.ApiUrlWhereUniqueInput
}

/**
 * ApiUrl findUniqueOrThrow
 */
export type ApiUrlFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter, which ApiUrl to fetch.
   */
  where: Prisma.ApiUrlWhereUniqueInput
}

/**
 * ApiUrl findFirst
 */
export type ApiUrlFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter, which ApiUrl to fetch.
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiUrls to fetch.
   */
  orderBy?: Prisma.ApiUrlOrderByWithRelationInput | Prisma.ApiUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApiUrls.
   */
  cursor?: Prisma.ApiUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApiUrls.
   */
  distinct?: Prisma.ApiUrlScalarFieldEnum | Prisma.ApiUrlScalarFieldEnum[]
}

/**
 * ApiUrl findFirstOrThrow
 */
export type ApiUrlFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter, which ApiUrl to fetch.
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiUrls to fetch.
   */
  orderBy?: Prisma.ApiUrlOrderByWithRelationInput | Prisma.ApiUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApiUrls.
   */
  cursor?: Prisma.ApiUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApiUrls.
   */
  distinct?: Prisma.ApiUrlScalarFieldEnum | Prisma.ApiUrlScalarFieldEnum[]
}

/**
 * ApiUrl findMany
 */
export type ApiUrlFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter, which ApiUrls to fetch.
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiUrls to fetch.
   */
  orderBy?: Prisma.ApiUrlOrderByWithRelationInput | Prisma.ApiUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApiUrls.
   */
  cursor?: Prisma.ApiUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiUrls.
   */
  skip?: number
  distinct?: Prisma.ApiUrlScalarFieldEnum | Prisma.ApiUrlScalarFieldEnum[]
}

/**
 * ApiUrl create
 */
export type ApiUrlCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * The data needed to create a ApiUrl.
   */
  data: Prisma.XOR<Prisma.ApiUrlCreateInput, Prisma.ApiUrlUncheckedCreateInput>
}

/**
 * ApiUrl createMany
 */
export type ApiUrlCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApiUrls.
   */
  data: Prisma.ApiUrlCreateManyInput | Prisma.ApiUrlCreateManyInput[]
}

/**
 * ApiUrl createManyAndReturn
 */
export type ApiUrlCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * The data used to create many ApiUrls.
   */
  data: Prisma.ApiUrlCreateManyInput | Prisma.ApiUrlCreateManyInput[]
}

/**
 * ApiUrl update
 */
export type ApiUrlUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * The data needed to update a ApiUrl.
   */
  data: Prisma.XOR<Prisma.ApiUrlUpdateInput, Prisma.ApiUrlUncheckedUpdateInput>
  /**
   * Choose, which ApiUrl to update.
   */
  where: Prisma.ApiUrlWhereUniqueInput
}

/**
 * ApiUrl updateMany
 */
export type ApiUrlUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApiUrls.
   */
  data: Prisma.XOR<Prisma.ApiUrlUpdateManyMutationInput, Prisma.ApiUrlUncheckedUpdateManyInput>
  /**
   * Filter which ApiUrls to update
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * Limit how many ApiUrls to update.
   */
  limit?: number
}

/**
 * ApiUrl updateManyAndReturn
 */
export type ApiUrlUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * The data used to update ApiUrls.
   */
  data: Prisma.XOR<Prisma.ApiUrlUpdateManyMutationInput, Prisma.ApiUrlUncheckedUpdateManyInput>
  /**
   * Filter which ApiUrls to update
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * Limit how many ApiUrls to update.
   */
  limit?: number
}

/**
 * ApiUrl upsert
 */
export type ApiUrlUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * The filter to search for the ApiUrl to update in case it exists.
   */
  where: Prisma.ApiUrlWhereUniqueInput
  /**
   * In case the ApiUrl found by the `where` argument doesn't exist, create a new ApiUrl with this data.
   */
  create: Prisma.XOR<Prisma.ApiUrlCreateInput, Prisma.ApiUrlUncheckedCreateInput>
  /**
   * In case the ApiUrl was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApiUrlUpdateInput, Prisma.ApiUrlUncheckedUpdateInput>
}

/**
 * ApiUrl delete
 */
export type ApiUrlDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
  /**
   * Filter which ApiUrl to delete.
   */
  where: Prisma.ApiUrlWhereUniqueInput
}

/**
 * ApiUrl deleteMany
 */
export type ApiUrlDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApiUrls to delete
   */
  where?: Prisma.ApiUrlWhereInput
  /**
   * Limit how many ApiUrls to delete.
   */
  limit?: number
}

/**
 * ApiUrl without action
 */
export type ApiUrlDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiUrl
   */
  select?: Prisma.ApiUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiUrl
   */
  omit?: Prisma.ApiUrlOmit<ExtArgs> | null
}
